version: 2

references:
  ignored-branches: &ignored-branches
     branches:
      ignore:
        - gh-pages

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: npm-install
          command: npm install

  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm run test

  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - add_ssh_keys:
          fingerprints:
            - "37:2e:93:9a:18:89:98:5c:86:ca:68:a4:9e:99:0b:1a"
      - checkout
      - run:
          name: deploy-gh-pages
          command: ./bin/deploy


workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            <<: *ignored-branches

      - test:
          filters:
            <<: *ignored-branches
          requires:
            - build

      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - test